version: '3.9'

volumes:

  postgres_data:

  redis_data:

  static_volume:

  media_volume:


services:

  web:

    container_name: django_docker
    image: django_docker_web:mwangihub_0.0.1

    build:
      context: ./web
      dockerfile: Dockerfile

    restart: always

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    expose:
      - 8050

    env_file:
      - web/.env

    ports:
      - "8050:8050"

    depends_on:
      - postgres_db

  postgres_db:

    restart: always

    container_name: django_docker_db

    image: django_docker_postgres:mwangihub

    build:

      context: ./web
      dockerfile: /scripts/postgres/Dockerfile

    command: -p 5434

    env_file:
      - web/.env

    expose:
      - 5434

    ports:
      - "5434:5434"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_service:

    restart: always

    container_name: django_docker_redis-service

    image: django_docker_redis-service:mwangihub

    build:
      context: ./web
      dockerfile: /scripts/redis/Dockerfile

    volumes:
      - redis_data:/data

    expose:
      - 6388

    ports:
      - "6388:6388"

    entrypoint: redis-server --appendonly yes --port 6388
